version: '3'
services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    restart: unless-stopped
    volumes:
      - srv:/srv/www/wordpress
    networks:
      - app-network
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file: .env  
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    depends_on:
      - db
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - srv:/srv/www/wordpress
    networks:
      - app-network

volumes:
  srv:
  dbdata:


networks:
  app-network:
    driver: bridge